### ISSUE TITLE
The connection speed of rdp mitm is a bit slower than the original rdp speed. How to improve this problem?

### ISSUE THREAD

**Issue by jiacheng9966** [GoSecure/pyrdp#161] opened 2019-11-02 00:48 UTC
**The connection speed of rdp mitm is a bit slower than the original rdp speed. How to improve this problem?**

**Comment by obilodeau** [comment] 2019-11-07 19:53
This issue is a duplicate of #162.

**Closed by obilodeau** 2019-11-07 19:53 UTC
Labels: duplicate
