### ISSUE TITLE
Refactor fast path bitmap code

### ISSUE THREAD

**Issue by xshill** [GoSecure/pyrdp#91] opened 2019-03-29 22:28 UTC
The fast path bitmap code is currently very confusing and could use some refactoring.

**Comment by alxbl** [comment] 2020-03-02 02:27
Hey @xshill, I'm currently working in the fastpath parsing code and I'd like more information on this:

What classes in particular do you feel need a refactor? Are you talking about the events parsing stuff in `parser/fastpath.py`, or in the bitmap handling code in the player?

Thanks,
Alex

**Comment by obilodeau** [comment] 2020-03-11 15:35
I don't think that the issue is useful since the refactoring steps were not outlined when the issue was reported. I'm not saying refactoring is not necessary but merely saying: if refactoring is required let's just do it, this issue doesn't explains the steps so it's not useful. Closing. @xshill feel free to re-open with concrete steps if you remember what they should be.

**Closed by obilodeau** 2020-03-11 15:35 UTC
Labels: refactor
