### ISSUE TITLE
24bpp makes the PyRDP player crash

### ISSUE THREAD

**Issue by Res260** [GoSecure/pyrdp#54] opened 2018-12-13 15:54 UTC
Tested with Liveplayer with FreeRDP --> win10 and win8 --> win10.

Its a free() error, so most likely due to a bug in rle.c when decompressing 24bpp bitmaps

Crashes after an undefined amount of time (seconds to minutes)

**Comment by alxbl** [comment] 2020-04-08 14:35
I haven't been able to reproduce this while testing in 24bpp for varying periods of time. I'm going to close this as cannot repro since we don't have support for 24bpp right now. Once we get around to adding proper 24+ bpp support, this bug might be re-opened or addressed during the testing phase.

If you have a call stack of the crash (Python and native, ideally) then feel free to re-open.

**Closed by alxbl** 2020-04-08 14:35 UTC
Labels: bug, low-priority

**Comment by Res260** [comment] 2020-04-08 15:10
With GDI, it should not be a problem to keep bitmaps downgraded to 16bpp I guess

**Comment by alxbl** [comment] 2020-04-08 15:27
I am planning to support 24 and 32bpp eventually. I'm closing this because with our without GDI, I was unable to reproduce the crash and you didn't give a callstack, so I have no idea how it could have happened. If you have a callstack feel free to add it, otherwise we'll reopen and address the bug if it ever comes up again. There's no point in tracking this until we have actual 24bpp support, though.
