### ISSUE TITLE
How can I get the account password saved in the mstsc connector

### ISSUE THREAD

**Issue by jiacheng9966** [GoSecure/pyrdp#178] opened 2020-01-31 08:13 UTC
How can I get the account password saved in the mstsc connector? To achieve this, do I need to set it in gpedis.msc? I myself tried using a lower version of mstsc.exe and everything was ok. But the username and password obtained by using mstsc.exe that comes with windows 10 is empty

**Comment by obilodeau** [comment] 2020-02-03 19:25
I assume this is a duplicate of #179. Closing.

**Closed by obilodeau** 2020-02-03 19:25 UTC
Labels: duplicate
