### ISSUE TITLE
Unable to listen connection

### ISSUE THREAD

**Issue by MMohtasham** [GoSecure/pyrdp#226] opened 2020-05-07 09:34 UTC
i am using the command pyrdp-mitm server-ip -i 127.0.0.1 -d port
and unable to listen connection, kindly help
how to use this??
![mitm](https://user-images.githubusercontent.com/48804428/81279226-4a916180-9070-11ea-803a-1a9d9ab90674.PNG)

**Comment by alxbl** [comment] 2020-05-11 18:31
I'm not sure what your question is?

PyRDP listens to 0.0.0.0:3389 by default, the `-i` and `-d` flags are meant to configure the address of a listening `pyrdp-player` instance. You will need to start PyRDP player and configure it with the right listening port so that the MITM is able to connect to it. 

If you want to change the listening port for the MITM, you need to use `-l` (lower case `L`)

**Comment by MMohtasham** [comment] 2020-05-18 05:05
my problem is that this pyrdp just listening continuous and not accept the connection what is proper syntax,?? means how write its syntax pyrdp-mitm.py server ip -i listening ip -d port , i am using this syntax but it unable to receive connection

**Comment by alxbl** [comment] 2020-05-21 12:51
Does it work when you connect directly to the MITM IP? If it doesn't, you most likely have a firewall blocking incoming connections.

If it does work, then everything is fine. The problem is likely that you need a way to redirect clients to your MITM to actually perform interception. PyRDP does not perform ARP spoofing or traffic redirection attacks, it only accepts connections and forwards them. As described [in the documentation][1], you need to use a tool like `bettercap` or `arpspoof` to force clients to connect to your MITM instead of the intended server.

[1]: https://github.com/GoSecure/pyrdp/blob/master/docs/bettercap-rdp-mitm.md

**Comment by MMohtasham** [comment] 2020-05-21 14:50
Which firewall is blocking my connection ubuntu or server 2012 R2.

**Comment by alxbl** [comment] 2020-05-21 15:54
I can't tell you that, you need to check your environment configuration and settings. In any case, I don't think this is an issue with PyRDP itself, so I'm closing it..

Please refer to bettercap's documentation about ARP spoofing and verify your environment to ensure it's setup properly. If you believe you did find a bug, please provide some debug output to help us located which part of the code is causing the issue.

Thanks,

**Closed by alxbl** 2020-05-21 15:54 UTC
