### ISSUE TITLE
pyrdp-mitm.py - invalid configuration with no fallback specified

### ISSUE THREAD

**Issue by zintegrity1121** [GoSecure/pyrdp#238] opened 2020-07-07 13:33 UTC
Hi All, 

I followed the installation settings from source but am receiving the following error. Would someone be able to help?
Python Version is 3.6.0

```
(venv) root@kali:~/Github/pyrdp/pyrdp/mitm# pyrdp-mitm.py
Traceback (most recent call last):
  File "/root/Github/pyrdp/venv/bin/pyrdp-mitm.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/Github/pyrdp/bin/pyrdp-mitm.py", line 17, in <module>
    from pyrdp.core.mitm import MITMServerFactory
  File "/root/Github/pyrdp/pyrdp/core/mitm.py", line 12, in <module>
    from pyrdp.mitm import MITMConfig, RDPMITM
  File "/root/Github/pyrdp/pyrdp/mitm/__init__.py", line 7, in <module>
    from pyrdp.mitm.cli import parseTarget, validateKeyAndCertificate
  File "/root/Github/pyrdp/pyrdp/mitm/cli.py", line 25, in <module>
    from pyrdp.mitm.config import DEFAULTS, MITMConfig
  File "/root/Github/pyrdp/pyrdp/mitm/config.py", line 103, in <module>
    DEFAULTS = settings.load(Path(__file__).parent.absolute() / "mitm.default.ini")
  File "/root/Github/pyrdp/pyrdp/core/settings.py", line 32, in load
    raise Exception('Invalid configuration with no fallback specified')
Exception: Invalid configuration with no fallback specified
(venv) root@kali:~/Github/pyrdp/pyrdp/mitm# 
```

**Comment by alxbl** [comment] 2020-07-16 00:11
It looks like the `mitm.default.ini` file is missing.

It should have been deployed when you installed. We probably have a bug in the install script and/or forgot to update the install instructions. For now you can copy the file manually to `/root/Github/pyrdp/pyrdp/mitm/mitm.default.ini`.

Let me know if that works for you. I'll check why this is happening tomorrow morning.

**Comment by alxbl** [comment] 2020-07-23 15:24
I tested this on a fresh build, but I wasn't able to reproduce. Can you give me the commit ID that you used and the exact commands?

Have you managed to get it working?

Cheers,

**Comment by alxbl** [comment] 2020-08-06 14:00
I've run into this issue yesterday. I'm going to try to investigate why it happens.

**Comment by alxbl** [comment] 2020-08-06 16:25
So it looks like there can be multiple root-causes, but mostly this appears to be a configuration issue:

- `repo/pyrdp/mitm/mitm.default.ini` should exist. If it doesn't, grab a copy from the repo or git clone/pull the latest master branch.
- If you're running the same install of pyrdp as root and low privilege user (for example to use TPROXY) make sure to use different pyrdp_output directories or that the low privilege user has write permission on the log files.

Note that log rotation could result in log files being owned by root if the log rotates during a high privilege execution. For this reason it's recommended to use different `pyrdp_output` directories.

----

I'm closing this as it appears to be a configuration issue and I've documented the workarounds here. Feel free to re-open if you are still having problems.

I also took the liberty of renaming this issue so that it can be found by people who run into the problem.

**Related Error messages**

```
Exception: Invalid configuration with no fallback specified
WARNING:root:Error Parsing PyRDP Configuration - Unable to configure handler 'mitm'
WARNING:root:Error Parsing PyRDP Configuration - Unable to configure handler 'ssl'
```

**Closed by alxbl** 2020-08-06 16:25 UTC
Labels: bug, investigate
